### ISSUE TITLE
Fonts folder

### ISSUE THREAD

**Issue by benenright** [torchbox/design-in-browser-bootstrap#10]
Add empty fonts folder.

**Comment by davecranwell** [comment]
This seems slightly at odds with #7, where you're suggesting we remove the components folder. Both are good practice, whether or not you personally use them. Seems we should have both, or neither, not one.

**Comment by benenright** [comment]
The components example was just not having a sub-folder in the CSS folder
(i just use a components.scss for all components) so I end up removing the
components folder.

Having a fonts folder is something we always use, so just thought be nice
if it's there by default (obvs separate from the css folder - so not sure
how they relate anyway?)


On 25 August 2015 at 12:20, Dave Cranwell <notifications@github.com> wrote:

> This seems slightly at odds with #7
> <https://github.com/torchbox/design-in-browser-bootstrap/issues/7>, where
> you're suggesting we remove the components folder. Both are good practice,
> whether or not you personally use them. Seems we should have both, or
> neither, not one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/torchbox/design-in-browser-bootstrap/issues/10#issuecomment-134557933>
> .
>



-- 
Ben Enright
Senior Designer
Torchbox Ltd <http://www.torchbox.com>

The Annexe, 4 Unity Street, Bristol, BS1 5HH
0117 359 1486

**Comment by davecranwell** [comment]
Blank folder added.
