### ISSUE TITLE
Gridle affecting browser reload speed

### ISSUE THREAD

**Issue by benenright** [torchbox/design-in-browser-bootstrap#13]
I've been using Gridle on my latest project, and it seems to have really slowed down the time it takes for the browser to auto-reload = reduced efficiency. 

I did a test by turning off the Gridle stuff, and it seemed to be quicker again.

Any ideas for how we can continue to use Gridle but get the speed up?

**Comment by davecranwell** [comment]
Having converted from Grunt to Gulp, I'm seeing significant speed increases.

Additionally if you're not relying on Gridle to generate classes for every grid permutation, comment out `@include gridle_generate_classes();` and you may see a further 50% reduction in compile time.

See: https://github.com/torchbox/design-in-browser-bootstrap/blob/master/site/src/scss/_grid.scss#L31
