### ISSUE TITLE
Markup changes not picked up for html files in subdirectories

### ISSUE THREAD

**Issue by helenb** [torchbox/design-in-browser-bootstrap#16]
If you have an includes folder with e.g. 'footer.html', changes to the markup don't get picked up until you restart gulp.

For example see the carerstrust-prototype repo on codebase, and try making a change to includes/in_this_section.html while running gulp.

**Comment by davecranwell** [comment]
I believe this is specific to that version of the bootstrap clone. Note line 13 of `gulpfile.js/config.js` in that project uses a non-recursive glob syntax to only look for `/*.html` i.e html files only at the root. It should be `src: src + "/**/*.html"` to indicate it should look in all folders. 

Also note that this repo is public so the mention of our clients is probably unwise (and why I didn't link to the line of code at fault)
