### ISSUE TITLE
Add a task for syncing fonts to dist directory

### ISSUE THREAD

**Issue by aaronmarruk** [torchbox/design-in-browser-bootstrap#24]
E.g., watch site/fonts and copy contents to dist/fonts on change.

**Comment by Loque-** [comment]
I have this on GW for the moment, will add to this repo so it can be removed/ignored instead of added! Thanks for the all reports!

**Comment by Loque-** [comment]
Thinkkkkkk I might leave this out for the moment as it hasn't been required for that many builds (think it came out on GW) and I am hoping the tooling and folder structure is clear enough for someone to add this on a case by case basis. Just incase;

 - Create a `fonts` folder in both `site` and `dist`
 - Open `package.json`;
   - under `config` add `"src_font": "site/fonts"` and `"dest_font": "dist/fonts"`
   - under `patternlab syncs` add `"sync:font": "rsync -rtvu --delete $npm_package_config_src_font/ $npm_package_config_dest_font/",`
   - under `watches` add "watch:font": "onchange $npm_package_config_src_font'/**/**' -- npm-run-all sync:font reload",
 - restart `npm run lab`

HTH!
