### ISSUE TITLE
Add all patterns to "All" view

### ISSUE THREAD

**Issue by aaronmarruk** [torchbox/design-in-browser-bootstrap#26]
Currently selecting "All" only displays the Atoms category – it would be helpful if we could look at all patterns in a single view.

**Comment by Loque-** [comment]
The menu is a little broken for some reason in patternlab also, am hoping as we use it overtime the issue will expose itself a bit more. Ideally we could re-write/fix the issues and improve to pass back.

**Comment by SimonDEvans** [comment]
This no longer appears to be an issue.
