### ISSUE TITLE
PostCSS adding source maps to css file

### ISSUE THREAD

**Issue by nicklee** [torchbox/design-in-browser-bootstrap#70]
If you're on version 4+ of postcss-cli it'll automatically add source maps to your css file. We already have source maps enabled in node-sass so you end up with a .map file from node-css and a source map inside your map.css which isn't ideal (normally more than doubling the file size of your production css).

You'll need to update the autoprefixer line in package.json to the following to sort it out:

"autoprefixer": "postcss --map false -u autoprefixer -b 'last 2 versions, iOS 8, > 3%' -r $npm_package_config_dest_css/*.css",

**Comment by helenb** [comment]
Thanks Nick. I will update the version in wagtail-kit rather than here as we're not making any further changes to dibb.

**Comment by helenb** [comment]
Actually, I'm not totally certain we even need postcss, as autoprefixer is called explictly anyway.

**Comment by nicklee** [comment]
my understanding is that autoprefixer is a plugin for postcss so it's required?

**Comment by helenb** [comment]
https://git.torchbox.com/internal/wagtail-kit/merge_requests/232
