### ISSUE TITLE
Header/Footer includes

### ISSUE THREAD

**Issue by benenright** [torchbox/design-in-browser-bootstrap#9]
Review if we need everything that is currently there / if everything we need to link to is correct by default:

eg, shall we remove:
<link rel="stylesheet" href="css/templates/homepage.css" />

Add default favicon.ico and link to it in header include.

**Comment by davecranwell** [comment]
I've now moved to the Swig templating system - like twig/liquid/jinja/django templating language - so the header/footer includes don't exist any more.

I think any references to the favicon are premature at the point that you'd be using this DIBB project most of the time - creating a favicon is a job for a designer, but implementing it right is pretty complicated these days and requires developer knowledge of the hosting setup to have it work properly.
